Repository hmcts/rd-user-profile-api, pull requests merged in 2019-12, with the labels that each got.

#206 RDCC-682 false positives fix
  audit.json
Labels: ns:rd-user-profile-api-pr-206

#211 Bump powermock-api-mockito2 from 1.7.4 to 2.0.4
  build.gradle
Labels: ns:rd-user-profile-api-pr-211

#212 Bump org.flywaydb.flyway from 5.0.7 to 6.1.0
  build.gradle
Labels: ns:rd-user-profile-api-pr-212

#214 RDCC-727: changing app version
  src/main/resources/application.yaml
Labels: ns:rd-user-profile-api-pr-214

#215 adding ia and fpl service name
  src/main/resources/application.yaml
Labels: ns:rd-user-profile-api-pr-215

#217 fix:pref test set up
  Jenkinsfile_CNP
Labels: ns:rd-user-profile-api-pr-217

#202 RDCC-682 nightly build fix
  Jenkinsfile_nightly
  audit.json
  config/owasp/suppressions.xml
  security.sh
Labels: ns:rd-user-profile-api-pr-202
