Repository hmcts/rd-user-profile-api, pull requests merged in 2019-06, with the labels that each got.

#7 Jenkins pr build fix
  Jenkinsfile_CNP
  charts/rd-user-profile-api/Chart.yaml
  charts/rd-user-profile-api/requirements.yaml
  charts/rd-user-profile-api/values.aat.template.yaml
  charts/rd-user-profile-api/values.preview.template.yaml
  charts/rd-user-profile-api/values.sandbox.template.yaml
  charts/rd-user-profile-api/values.yaml
  docker-compose.yml
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/perftest.tfvars
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/AbstractFunctional.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/CreateUserProfileFuncTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/RetrieveUserProfileFuncTest.java
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:rd-user-profile-api-pr-7

#8 Fix for Master build
  infrastructure/main.tf
  src/main/resources/bootstrap.yaml
Labels: ns:rd-user-profile-api-pr-8

#10 Fix for Database vault key name
  infrastructure/main.tf
Labels: ns:rd-user-profile-api-pr-10

#11 Fixing vault keys to read DB username
  infrastructure/main.tf
Labels: ns:rd-user-profile-api-pr-11

#12 JENKINS-MASTER-FIX: build pipe line issue fixed
  build.gradle
Labels: ns:rd-user-profile-api-pr-12

#9 RDCC-318 Populate resource table both happy/unhappy path and alos covering exception handling
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/CreateNewUserProfileIntTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/CreateNewUserProfileWithIdamErrorsIntTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileIntTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileInternalServerErrorIntTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileWithIdamErrorsIntTest.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/IdamRegistrationInfo.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/IdamRolesInfo.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/entities/Audit.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/entities/UserProfile.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/service/IdamService.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/service/IdamServiceException.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/service/IdentityManagerService.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/service/ResourceRetriever.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/service/UserProfileCreator.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/service/UserProfileRetriever.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/service/UserProfileService.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/infrastructure/clients/ResponseSource.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/infrastructure/controllers/UserProfileController.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/infrastructure/controllers/advice/ErrorConstants.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/infrastructure/controllers/advice/ErrorResponse.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/infrastructure/controllers/advice/UserProfileControllerAdvice.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/infrastructure/repository/AuditRepository.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/util/IdamStatusResolver.java
  src/main/resources/application.yaml
  src/main/resources/db/migration/V1.0.0__init_tables.sql
  src/test/java/uk/gov/hmcts/reform/userprofileapi/domain/entities/UserProfileTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/domain/service/IdamServiceExceptionTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/domain/service/UserProfileCreatorTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/domain/service/UserProfileRetrieverTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/domain/service/UserProfileServiceTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/infrastructure/clients/IdamServiceTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/infrastructure/controllers/advice/UserProfileControllerAdviceTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/util/IdamStatusResolverTest.java
Labels: ns:rd-user-profile-api-pr-9
