Repository hmcts/rd-user-profile-api, pull requests merged in 2020-12, with the labels that each got.

#582 Added method call to sync branches
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-582

#586 build: Upgraded httpclient and hibernate-core versions to fix CVE-2020-13956 and CVE-2020-25638
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-586

#589 build: Addressed CVE 2020-17521 by upgrading groovy
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-589

#588 DTSPO-266 Enable self service read only access
  infrastructure/main.tf
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-588

#592 Bump : RDCC-2017 -Upgrade Jar versions
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-592
