Repository hmcts/rd-user-profile-api, pull requests merged in 2021-11, with the labels that each got.

#735 fix: RDCC-3557 Upgraded springboot version to fix CVE-2021-22096
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-735

#736 Added postgresql_version
  infrastructure/main.tf
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-736

#738 Create postgres v11 DB on all environments
  infrastructure/main.tf
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-738

#742 CHG5006041 - Add secret to store v11 DB secrets
  infrastructure/main.tf
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-742

#743 Update configurations to point to v1 DB
  charts/rd-user-profile-api/Chart.yaml
  charts/rd-user-profile-api/values.aat.template.yaml
  charts/rd-user-profile-api/values.yaml
  infrastructure/main.tf
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-743

#744 Publish Reports in Jenkins
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-744

#746 Remove v9.6 DB and temporary v11 secret
  infrastructure/main.tf
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-746
