Repository hmcts/rd-user-profile-api, pull requests merged in 2021-08, with the labels that each got.

#721 RDCC-3168: Addressing Sonar Issues in Master
  src/test/java/uk/gov/hmcts/reform/userprofileapi/util/JsonFeignResponseHelperTest.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-721

#722 RDCC-3169 - Update chart versions in all PRD repos
  charts/rd-user-profile-api/Chart.yaml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-722

#723 RDCC-3237 - Fix CVE issue : CVE-2021-28170
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-723

#724 RDCC-3237 - Fix CVE issues CVE-2021-22119
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-724

#726 RDCC-3254 - Suppressed CVE-2020-23171
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-726

#727 RDCC-3239- Fix Security scan issue
  security.sh
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-727

#728 fix: Nightly build failure and use fixed version for azuread
  audit.json
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-728
