Repository hmcts/rd-user-profile-api, pull requests merged in 2021-07, with the labels that each got.

#716 changed the order of command in security.sh to fix security scan
  security.sh
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-716

#715 Add auto-update config for PR branches
  .github/workflows/autoupdate.yml
Labels: DO NOT MERGE, ns:rd, prd:rd, rel:rd-user-profile-api-pr-715

#717 RDCC-3141 : fix CVE-2021-33037
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-717

#718 fix : remove bintray reference(RDCC-3150)
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-718

#719 RDCC-2820: Deprecation of Email as a Query Param in APIs
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/UserProfileFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/client/FuncTestRequestHandler.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileIntTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileInternalServerErrorIntTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileWithIdamErrorsIntTest.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileController.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileUtil.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileControllerTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileUtilTest.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-719

#720 RDCC-3167 - fix security scan
  audit.json
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-720
