Repository hmcts/rd-user-profile-api, pull requests merged in 2021-06, with the labels that each got.

#703 RDCC-2838 - changed all Gradle 7 deprecated entries
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-703

#709 upgraded spring boot version from 2.4.5 to 2.4.6 to fix cvv
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-709

#712 RDCC-2986-UP API: Update Jenkins nightly file to generate the serenit…
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-712
