Repository hmcts/rd-user-profile-api, pull requests merged in 2021-03, with the labels that each got.

#644 fix: RDCC-2507 Upgraded spring boot version to fix CVE CVE-2021-22112
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-644

#643 Update app insights key secret name
  charts/rd-user-profile-api/Chart.yaml
  charts/rd-user-profile-api/values.preview.template.yaml
  charts/rd-user-profile-api/values.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-643

#649 fix: RDCC-2581: Fixed CVEs CVE-2021-25122, CVE-2021-25329
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-649

#657 RDCC-1985: removing unwanted suppressions
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-657

#658 fix:RDCC-2632 added hikari configuration
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-658
