Repository hmcts/rd-user-profile-api, pull requests merged in 2021-09, with the labels that each got.

#730 Add fortify implementation
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-730

#729 Nightly Build Fix: Adding entries to audit.json
  audit.json
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-729

#731 RDCC-3277: Removed hard coded string in the configuration files.
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  bin/run-in-docker.sh
  charts/rd-user-profile-api/Chart.yaml
  charts/rd-user-profile-api/values.preview.template.yaml
  charts/rd-user-profile-api/values.yaml
  docker-compose.yml
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/util/CustomSerenityRunner.java
  src/functionalTest/resources/application-functional.yaml
  src/integrationTest/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/userprofileapi/config/ServiceTokenGeneratorConfiguration.java
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-731
