Repository hmcts/rd-user-profile-api, pull requests merged in 2021-12, with the labels that each got.

#747 fix: RDCC-3655 Replaced valid email domain in test classes with dummy email domain
  src/contractTest/java/uk/gov/hmcts/reform/userprofileapi/IdamConsumerTest.java
  src/contractTest/java/uk/gov/hmcts/reform/userprofileapi/UserProfileProviderTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/client/UserProfileRequestHandlerTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/AddAndDeleteRolesWithIdamIntTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/AuthorizationEnabledIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/CreateNewUserProfileIntTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/CreateNewUserProfileWithDuplicateUserIntTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveMultipleUserProfilesIntTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileIntTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileInternalServerErrorIntTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/UpdateUserProfileIntTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/request/IdamRegisterUserRequestTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/domain/IdamRolesInfoTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/domain/entities/UpdatedUserDetailsTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/resource/UserProfileIdentifierTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileRetrieverTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileUpdatorTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/ValidationHelperServiceTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/ValidationServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/util/IdamStatusResolverTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileMapperTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileUtilTest.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-747

#748 RDCC-3768: Disabled fortify scan until further notice
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-748

#749 fix: RDCC-3773 patch log4j to the latest version
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-749

#751 RDCC-3799: upgrading log4j to '2.16.0'
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-751

#752 RDCC-3786: Collating Dependabot PRs
  .dependabot/config.yml
  .github/dependabot.yml
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-752

#764 Fix: Upgrading log4j to fix CVE-2021-45105
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-764
