Repository hmcts/rd-user-profile-api, pull requests merged in 2022-04, with the labels that each got.

#807 RDCC-4350: Java 17 Migration
  Dockerfile
  build.gradle
  docker-compose.yml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-807

#809 RDCC-4395: CVE & Mutation Fixes
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-809

#810 Nightly build issues
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-810

#811 UP - Handle Verbose Error Messages
  src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/advice/UserProfileControllerAdvice.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/advice/UserProfileControllerAdviceTest.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-811

#814 cve fix for spring core
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-814
