Repository hmcts/rd-user-profile-api, pull requests merged in 2022-09, with the labels that each got.

#890 Add missing env vars
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-890

#891 RDCC-5392: adding suppression for `CVE-2022-25857`
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-891

#892 Adding logging level
  src/main/java/uk/gov/hmcts/reform/userprofileapi/config/RestAuthenticationEntryPoint.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/config/SecurityEndpointFilter.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/oidc/JwtGrantedAuthoritiesConverter.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-892

#894 Enable Tomcat access logs
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-894

#895 Loggers to identify idam call
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/IdamServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileRetriever.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-895

#898 Upgrade IDAM Java client
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-898

#899 Increase IDAM client timeout
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-899

#900 Drop duplicate index on Idam_id
  src/main/resources/db/migration/V1_7__drop_index_for_idam_id.sql
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-900

#901 Nightly Fix: Updating security.sh
  security.sh
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-901
