Repository hmcts/rd-user-profile-api, pull requests merged in 2022-02, with the labels that each got.

#768 Upgrade Gradle 7.3.3
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-768

#771 fix: Used used testImplementation instead of testCompile
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-771

#770 CVE-2018-1258 CVE fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-770

#772 fixed sonar minor issues
  src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/request/UserProfileDataRequestTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/response/UserProfileDataResponseTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/repository/AuditRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/resource/UpdateUserProfileDataTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileCreatorTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileRetrieverTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileUpdatorTest.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-772

#774 RDCC-4048: CVE Fixes
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-774

#773 idam bearer token logging
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/UserProfileFunctionalTest.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/config/RestAuthenticationEntryPoint.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/config/SecurityConfiguration.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-773

#769 feat: RDCC-3951 Update both attributes and roles
  src/contractTest/java/uk/gov/hmcts/reform/userprofileapi/UserProfileProviderTest.java
  src/contractTest/java/uk/gov/hmcts/reform/userprofileapi/UserProfileProviderTestConfiguration.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/AbstractFunctional.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/UserProfileFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/client/IdamOpenIdClient.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileController.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/ResourceCreator.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/ResourceUpdator.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileCreator.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileService.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileUpdator.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileControllerTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileCreatorTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileServiceTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileUpdatorTest.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-769

#775 fix: Nightly build failure
  audit.json
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-775

#777 RDCC-4088: Fixing CWE
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-777

#779 fix: Removed hard coded secret
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  src/functionalTest/resources/application-functional.yaml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-779
