Repository hmcts/rd-user-profile-api, pull requests merged in 2022-03, with the labels that each got.

#778 RDCC-4040 UP: Completeness of functional and Integration test
  src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/FeatureToggleServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileServiceTest.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-778

#780 fix: Updated java chart version to 3.7.3
  charts/rd-user-profile-api/Chart.yaml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-780

#792 fix: Ignored the fortify build failure
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-792

#793 RDCC-4263: Fixing CVE-2020-36518
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-793

#794 RDCC-4299: Collating DependaBot PRs
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-794

#805 RDCC-4331 updated for cve 2020-36518
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-805

#808 RDCC-4380 CVE Fix
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-808
