Repository hmcts/rd-user-profile-api, pull requests merged in 2022-08, with the labels that each got.

#875 Address CVE-2020-23171 for all refdata REPOs
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-875

#876 RDCC-5261: Upgrading `postgresql` to `42.4.1`
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-876

#879 Adding Loggers to the roles endpoint
  src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileController.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/IdamServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileRetriever.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-879

#881 Use latest agent
  Dockerfile
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-881

#882 Upgrade feign client
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-882

#883 loggers debug mode
  src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileController.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/IdamServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileRetriever.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-883

#884 Adding logging level
  charts/rd-user-profile-api/Chart.yaml
  charts/rd-user-profile-api/values.yaml
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-884

#885 Upgrade Launch Darkly client
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-885

#888 Added more logging in controller
  charts/rd-user-profile-api/Chart.yaml
  charts/rd-user-profile-api/values.aat.template.yaml
  src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileController.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-888
