Repository hmcts/rd-user-profile-api, pull requests merged in 2022-05, with the labels that each got.

#816 RDCC-4633: Upgrading `launchDarklySdk` to `5.8.1` (CVE-2022-25647 Fix)
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-816

#815 Feat:Changes made to fix app-insights issue
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/UserProfileFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/serenity5/SerenityTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/serenity5/SerenityTestWithoutReporting.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/serenity5/counter/TestCountListener.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/serenity5/counter/TestCounter.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/serenity5/extension/SerenityExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/serenity5/extension/SerenityJUnitLifecycleAdapterExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/serenity5/extension/SerenityManualExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/serenity5/extension/SerenityReportExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/serenity5/extension/SerenityStepExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/serenity5/extension/page/PatchedManagedWebDriverAnnotatedField.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/serenity5/extension/page/SerenityPageExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/serenity5/extension/page/TestConfiguration.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/serenity5/extension/page/TestMethodAnnotations.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/serenity5/guice/JUnit5Module.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/serenity5/guice/JUnitInjectors.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-815

#817 RDCC-4690: Suppressing `CVE-2016-1000027`
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-817

#818 RDCC-4699: Upgrading `tomcat.embed` to `9.0.63` (`CVE-2022-29885` Fix)
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-818
