Repository hmcts/rd-user-profile-api, pull requests merged in 2022-06, with the labels that each got.

#821 Feat:To handle 500 HTTP responses
  src/main/java/uk/gov/hmcts/reform/userprofileapi/config/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/config/SecurityEndpointFilter.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/exception/UnauthorizedException.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/repository/IdamRepository.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/exception/UnauthorizedExceptionTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/repository/IdamRepositoryTest.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-821

#824 config: RDCC-4820 Configured renovate
  renovate.json
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-824

#838 RDCC-4857:UP API Automerge Renovate PR's
  .github/workflows/combine-prs.yml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-838

#867 RDCC-4945 Delete dependabot yaml file
  .github/dependabot.yml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-867

#868 cve fix for tomcat embed
  charts/rd-user-profile-api/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-868
