Repository hmcts/rd-user-profile-api, pull requests merged in 2023-03, with the labels that each got.

#934 RDCC-6464: Adding Suppression for `CVE-2023-24998`
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-934

#932 RDCC-6421 Add renovate.json
  .github/renovate.json
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-932

#929 Spring boot upgrade to 2.7.7 RDCC-6338
  Dockerfile
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/docs/SwaggerPublisherTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/AuthorizationEnabledIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/SpringBootIntegrationTest.java
  src/integrationTest/resources/application-test.yml
  src/main/java/uk/gov/hmcts/reform/userprofileapi/config/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileController.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/WelcomeController.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/oidc/JwtGrantedAuthoritiesConverter.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/userprofileapi/oidc/JwtGrantedAuthoritiesConverterTest.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-929

#936 security scan issue
  audit.json
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-936

#939 Rdcc 6517
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-939

#938 RDCC-6521 - Upgrade Libs
  build.gradle
  infrastructure/.terraform-version
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, add-or-update, rel:rd-user-profile-api-pr-938

#953 Addressing NPE for user without roles - User Profile API
  src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/entities/UserProfile.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/domain/entities/UserProfileTest.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-953

#951 Feat:Address CVEs in all Reference Data repositories - User Profile
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-951

#937 Staff : Update the user details in UP
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/AuthorizationEnabledIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/ReInviteUserProfileIntTest.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileController.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/ResourceCreator.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/ValidationHelperService.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileCreator.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileService.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/ValidationHelperServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileControllerTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileCreatorTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileServiceTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/ValidationHelperServiceTest.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-937

#956 Nightly build failure
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-956

#957 Nightly build failure
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-957
