Repository hmcts/rd-user-profile-api, pull requests merged in 2023-04, with the labels that each got.

#954 RDCC-6528: Addressing Sonar Issues
  src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileController.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/WelcomeController.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/UserProfileQueryProvider.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/IdamServiceImpl.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-954

#959 RDCC-6525: Adding unit tests to increase Mutation Coverage
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/IdamServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileCreator.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/util/FeatureConditionEvaluation.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/IdamServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileCreatorTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/util/FeatureConditionEvaluationTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/util/JsonFeignResponseUtilTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileMapperTest.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-959

#960 DTSRD 75: update URLs for Preview and AAT
  Jenkinsfile_CNP
  security.sh
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-960

#961 Fix nightly build with audit.json change
  audit.json
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-961

#962 Fix nightly build with audit.json change
  audit.json
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-962

#963 Fix nightly build with audit.json change
  audit.json
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-963

#964 DTSRD-213 - add ignore to audit.json for 10096_Timestamp
  audit.json
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-964

#965 DTSRD-235 - update build.gradle for verifying pact and publish results
  Jenkinsfile_CNP
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-965

#966 DTSRD-248 - update expired token error message
  src/main/java/uk/gov/hmcts/reform/userprofileapi/util/IdamStatusResolver.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-966

#968 UserProfileAPI:WireMock response enhancement
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/AddAndDeleteRolesWithIdamIntTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/AuthorizationEnabledIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/CreateNewUserProfileWithDuplicateUserIntTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveMultipleUserProfilesIntTest.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-968
