Repository hmcts/rd-user-profile-api, pull requests merged in 2023-11, with the labels that each got.

#1003 Master build failure fix
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-1003

#1004 Update application.yaml to add schema to connection string
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-1004

#1006 Update application.yaml .reverting connection string changes
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-1006

#1007 DTSRD-1466.Updating schema parameter with hibernate
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-1007

#1005 [RDCC-7097]UP : Consumer Pact Test Cases needs to be added
  src/contractTest/java/uk/gov/hmcts/reform/userprofileapi/UserProfileProviderTest.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-1005

#1008 Update acb.tpl.yaml
  acb.tpl.yaml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-1008
