Repository hmcts/rd-user-profile-api, pull requests merged in 2023-02, with the labels that each got.

#925 RDCC-6259: Adding & Upgrading Dependencies
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-925

#927 User profile API to retrieve user profile details
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/UserProfileFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileIntTest.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileController.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/response/UserIdamStatusWithEmail.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/response/UserIdamStatusWithEmailResponse.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/entities/UserProfileIdamStatus.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/repository/UserProfileRepository.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/ResourceRetriever.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/UserProfileQueryProvider.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileRetriever.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileService.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileControllerTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileQueryProviderTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileRetrieverTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileServiceTest.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-927

#930 RDCC-6410: adding entries to `audit.json`
  audit.json
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-930

#931 RDCC-6374: Upgrading chart version to latest
  charts/rd-user-profile-api/Chart.yaml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-931

#933 RDCC-6432: Adding Suppression for `CVE-2022-45688`
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-933
