Repository hmcts/rd-user-profile-api, pull requests merged in 2023-06, with the labels that each got.

#979 Suppress CVE-2023-20883
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-979

#980 Update renovate
  renovate.json
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-980

#978 Update README.md
  README.md
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-978

#981 [RDCC-6819]SonarQube Issue fix
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileUpdator.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileCreatorTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/util/FeatureConditionEvaluationTest.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-981

#982 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-982
