Repository hmcts/rd-user-profile-api, pull requests merged in 2023-05, with the labels that each got.

#958 Upgraded to gradle wrapper 7.4.2
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-958

#972 [RDCC-6201]- Delete functional Test data - User profile.
  Jenkinsfile_nightly
  deletescript/sql/delete-functional-data-script.sql
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-972

#977 DTSRD-456: fix CVE-2023-28709
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-977
