Repository hmcts/rd-user-profile-api, pull requests merged in 2023-10, with the labels that each got.

#994 DTSRD-1262.Upgrade Postgres to V15
  infrastructure/main.tf
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, add-or-update, rel:rd-user-profile-api-pr-994

#995 DTSRD-1262 . Upgrade postgres
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, add-or-update, rel:rd-user-profile-api-pr-995

#996 DTSRD-1466.Remove branches to sync -userprofile demo and master
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-996

#997 DTSRD-1466. Remove branches to sync -judicial demo and master
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-997

#999 Addresses CVE-2023-42794, CVE-2023-42795 and CVE-2023-45648
  build.gradle
  charts/rd-user-profile-api/Chart.yaml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-999

#1002 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-1002
