Repository hmcts/rd-user-profile-api, pull requests merged in 2024-07, with the labels that each got.

#1062 DTSRD-3041
  src/main/resources/testcontainers.properties
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-1062

#1064 Update .terraform-version
  infrastructure/.terraform-version
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, aat/add-or-update, prod/add-or-update, rel:rd-user-profile-api-pr-1064

#1063 Dtsrd 3041
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  src/main/resources/testcontainers.properties
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-1063

#987 Spring boot 3 upgrade
  build.gradle
  charts/rd-user-profile-api/values.preview.template.yaml
  database/Dockerfile
  gradle.properties
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/AbstractFunctional.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/UserProfileFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/config/TestConfigProperties.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/ProfileConfig.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/docs/SwaggerPublisherTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/AuthorizationEnabledIntegrationTest.java
  src/integrationTest/resources/application-test.yml
  src/main/java/uk/gov/hmcts/reform/userprofileapi/Application.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/config/AccessDecisionManagerAuthorizationManagerAdapter.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/config/FeignConfiguration.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/config/FeignInterceptorConfiguration.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/config/MethodSecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/config/RestAuthenticationEntryPoint.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/config/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/config/SecurityEndpointFilter.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileController.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/advice/UserProfileControllerAdvice.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/entities/Audit.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/entities/UserProfile.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/feign/IdamFeignClient.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/resource/UserProfileCreationData.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/FeatureToggleServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileUpdator.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/util/FeatureConditionEvaluation.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/util/IdamStatusResolver.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileUtil.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/UserProfileControllerTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/controller/advice/UserProfileControllerAdviceTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/service/impl/UserProfileUpdatorTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/util/FeatureConditionEvaluationTest.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileUtilTest.java
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-987, enable_keep_helm

#1088 Update build.gradle . Fix Build
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-1088
