Repository hmcts/rd-user-profile-api, pull requests merged in 2024-10, with the labels that each got.

#1114 DTSRD-3562 Swagger Publishing
  .github/workflows/swagger.yml
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/docs/SwaggerPublisherTest.java
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-1114

#1115 DTSRD-3580 Jenkins Test Reports to Publish on Failure
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-1115

#1116 DTSRD-3623
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-1116

#1117 DTSRD-3619
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-1117

#1118 DTSRD-3583 PI Test Version Config - pitestVersion added to pitest con…
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-user-profile-api-pr-1118
