Repository hmcts/rd-user-profile-api, pull requests merged in 2024-06, with the labels that each got.

#1049 Update azurerm to 3.105.0
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, aat/add-or-update, prod/add-or-update, rel:rd-user-profile-api-pr-1049

#1052 DTSRD-2895
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, aat/add-or-update, prod/add-or-update, rel:rd-user-profile-api-pr-1052

#1061 DTSRD-2845: Resize PG flexible server instance
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, aat/add-or-update, prod/add-or-update, rel:rd-user-profile-api-pr-1061
