Repository hmcts/rd-user-profile-api, pull requests merged in 2025-01, with the labels that each got.

#1123 CME-253: Database monitoring and alerting on RD repositories
  Jenkinsfile_CNP
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, aat/add-or-update, prod/add-or-update, rel:rd-user-profile-api-pr-1123

#1124 CME-293: Update azurerm
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, aat/add-or-update, prod/add-or-update, rel:rd-user-profile-api-pr-1124

#1125 Update to spring-boot 3.3.7
  build.gradle
Labels: ns:rd, prd:rd

#1121 CME-201 bump rd-commons-lib
  .travis.yml
  Dockerfile
  README.md
  build.gradle
  config/owasp/suppressions.xml
  database/Dockerfile
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/UserProfileFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/userprofileapi/util/FeatureToggleConditionExtension.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/docs/SwaggerPublisherTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/AuthorizationEnabledIntegrationTest.java
  src/integrationTest/resources/application-test.yml
  src/main/java/uk/gov/hmcts/reform/userprofileapi/Application.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/config/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/controller/request/UpdateUserDetails.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/entities/UpdatedUserDetails.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/domain/entities/UserProfile.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/util/FeatureConditionEvaluation.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/util/IdamStatusResolver.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileMapper.java
  src/main/java/uk/gov/hmcts/reform/userprofileapi/util/UserProfileValidator.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/helper/CreateUserProfileTestDataBuilder.java
  src/test/java/uk/gov/hmcts/reform/userprofileapi/helper/UserProfileTestDataBuilder.java
  src/test/resources/application.yml
  web.config
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-user-profile-api-pr-1121
